/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.EmployeeRole;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mohab
 */
public class AddProduct extends Add {

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        super("ProductId","Product Name","Manufacturer Name","Supplier Name","Quantitu","Price",false);
        this.setTitle("Add Products");
        initComponents();
    }
    


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add Product");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
    @Override
    protected void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
    {
        super.jButton1ActionPerformed(evt);
         if(t1.isEmpty()||t2.isEmpty()||t3.isEmpty()||t4.isEmpty()||t5.isEmpty()||t6.isEmpty())
                JOptionPane.showMessageDialog(null, "Some Fields are empty");
         else
         {
        boolean isNumeric = true;
        int q=0;
        try{
            q = Integer.parseInt(t5);
        }
        catch(NumberFormatException e){
            isNumeric = false;
        }
        if(!isNumeric)
        {
           JOptionPane.showMessageDialog(null, "You should enter a numneric integer value in the field Quantity");
           return;
           
        }
        boolean isNumeric2 = true;
        float p=0;
        try{
            p = Float.parseFloat(t6);
            
        }catch(NumberFormatException e)
        {
        isNumeric2 = false;
        }
        if(!isNumeric2)
        {
             JOptionPane.showMessageDialog(null, "You should enter a numneric float value in the field Quantity");
           return;
        }
        boolean adding = Employee_Role.emp.addProduct(super.t1, super.t2,super.t3,super.t4,q,p);
        if(!adding)
        {
            JOptionPane.showMessageDialog(null, "The product with the Id " + super.t1+" already exists!");
        }
        else
        {
         JOptionPane.showMessageDialog(null, "The product with the Id " + super.t1+" was successfully added");
         ((JFrame)getParentNode()).setVisible(true);
         setVisible(false);
        }
         }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            EmployeeRole emp;
            @Override
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


}
